M48
; DRILL file {KiCad (6.0.0)} date Tue Jul 19 14:30:05 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-19T14:30:05+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X45.0Y-66.0
X45.0Y-114.0
X146.0Y-66.0
X146.0Y-114.0
T0
M30
