M48
; DRILL file {KiCad (6.0.0)} date Sun Jun 26 22:50:54 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-26T22:50:54+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X39.0Y-40.0
X39.0Y-54.0
X171.0Y-40.0
X171.0Y-54.0
T0
M30
